name = "MintBundle"
client_id = "7578b7387ba113d6c4979f4afa04b15c"
application_url = "https://app.mintbundle.app"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_inventory,write_inventory,read_customers,read_themes,write_cart_transforms,read_locations"

[auth]
redirect_urls = [ "https://app.mintbundle.app/api/auth/callback" ]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks"

[app_proxy]
url = "https://app.mintbundle.app/api/proxy"
subpath = "mintbundle"
prefix = "apps"

[pos]
embedded = false

[build]
include_config_on_deploy = true
